### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by aspnetcs** [zhyhan/AD3DMIL#1]
Would you like to provide the dataset for testing?

**Comment by zhyhan** [comment]
Sorry， the dataset is privacy-preserving by the hospital.

**Comment by aspnetcs** [comment]
能给出一个示例数据集吗？不然，程序没法运行，咋办？













--




在 2022-11-22 13:33:21，"Zhongyi Han" ***@***.***> 写道：

Closed #1 as completed.

**Comment by zhyhan** [comment]
I am sorry for the inconvenience caused by the private data collected from real COVID-19 patients. You may refer to existing public datasets, such as the Kaggle dataset: https://www.kaggle.com/datasets/andrewmvd/covid19-ct-scans. The first step is the segmentation using 3D-Unet, which is easily applicable.

**Comment by aspnetcs** [comment]
好的，我先试试













--




At 2022-11-22 16:10:25, "Zhongyi Han" ***@***.***> wrote:

I am sorry for the inconvenience caused by the private data collected from real COVID-19 patients. You may refer to existing public datasets, such as the Kaggle dataset: https://www.kaggle.com/datasets/andrewmvd/covid19-ct-scans. The first step is the segmentation using 3D-Unet, which is easily applicable.

**Comment by aspnetcs** [comment]
3D-Unet在哪里？https://github.com/pykao/Modified-3D-UNet-Pytorch  是这个吗？













--




At 2022-11-22 16:10:25, "Zhongyi Han" ***@***.***> wrote:

I am sorry for the inconvenience caused by the private data collected from real COVID-19 patients. You may refer to existing public datasets, such as the Kaggle dataset: https://www.kaggle.com/datasets/andrewmvd/covid19-ct-scans. The first step is the segmentation using 3D-Unet, which is easily applicable.

**Comment by zhyhan** [comment]
Segmentation of lung masks: preprocess/seg.py for binary classification and preprocess/seg-multi-class.py for multi-class classification;

**Comment by aspnetcs** [comment]
好的，我试一下













--




At 2022-11-23 08:42:10, "Zhongyi Han" ***@***.***> wrote:

Segmentation of lung masks: preprocess/seg.py for binary classification and preprocess/seg-multi-class.py for multi-class classification;

**Comment by aspnetcs** [comment]
***@***.***:/home/AD3DMIL-master/preprocess# python seg.py ../../COVID-CT-master/Images-processed/CT_COVID/kjr-21-e24-p2-8.png

  File "seg.py", line 18

    sys.exit(f'File not found: {string}')

                                       ^

SyntaxError: invalid syntax

用seg.py分割，怎么错了？如何使用这个seg.py进行分割？







--




At 2022-11-23 08:42:10, "Zhongyi Han" ***@***.***> wrote:

Segmentation of lung masks: preprocess/seg.py for binary classification and preprocess/seg-multi-class.py for multi-class classification;

**Comment by zhyhan** [comment]
png图片格式好像不行，需要3D的CT数据，请查看具体的dataloader需求格式

**Comment by aspnetcs** [comment]
好的，我再试试













--




在 2022-11-24 13:37:01，"Zhongyi Han" ***@***.***> 写道：

png图片格式好像不行，需要3D的CT数据，请查看具体的dataloader需求格式

**Comment by aspnetcs** [comment]
***@***.***:/home/AD3DMIL-master/preprocess# python seg.py ../../kaggle-covid/ct_scans/coronacases_org_001.nii

  File "seg.py", line 18

    sys.exit(f'File not found: {string}')

                                       ^

SyntaxError: invalid syntax




kaggle-covid/ct_scans/coronacases_org_001.nii  文件都是从kaggle上下载的 covid-19 文件，但是这样分割也出错了，nii是3d文件？咋办？




--




在 2022-11-24 13:37:01，"Zhongyi Han" ***@***.***> 写道：

png图片格式好像不行，需要3D的CT数据，请查看具体的dataloader需求格式
